---
- name: Add backports preferences
  template:
    src: etc/apt/preferences.d/backports.j2
    dest: /etc/apt/preferences.d/01backports
    mode: 0644

- name: Add backports repository
  apt_repository:
    repo: "deb {{ _prepi_backports_url }} {{ _prepi_backports_release }} main non-free contrib"
    filename: backports.list
    mode: 0644
