---
- name: Remove orphan dependencies, etc...
  shell:
    cmd: |
      apt-get --purge remove $(deborphan) -y
      sync
    executable: /bin/bash
    warn: no
  changed_when: no

- name: Packages cleaning
  shell:
    cmd: |
      apt-get autoremove -y
      apt-get autoclean -y
      apt-get clean
    executable: /bin/bash
