---
- name: Update kernel and firmware
  environment:
    BRANCH: "{{ prepi_firmware_branch }}"
    PRUNE_MODULES: 1
  shell:
    cmd: echo y | rpi-update
    executable: /bin/bash
  changed_when: no
  register: firmware

- name: Set EEPROM release
  lineinfile:
    path: /etc/default/rpi-eeprom-update
    regexp: "^FIRMWARE_RELEASE_STATUS="
    line: 'FIRMWARE_RELEASE_STATUS="{{ prepi_eeprom }}"'

- name: Update EEPROM
  command: |
    rpi-eeprom-update -a
  changed_when: no
  register: eeprom

- name: Set eeprom_reboot and firmware_reboot facts
  set_fact:
    eeprom_reboot: "{{ eeprom.stdout | regex_search('reboot') }}"
    firmware_reboot: "{{ firmware.stdout | regex_search('reboot') }}"

- name: Reboot the Raspberry Pi and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 120
    post_reboot_delay: 5
    test_command: whoami
  when:
    - eeprom_reboot | length > 0 or firmware_reboot | length > 0
    - prepi_reboot | bool
