---
- name: Install pulseaudio sound server
  package:
    name:
      - pulseaudio
      - pulseaudio-utils
  become: yes

- name: Create PulseAudio directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "/home/{{ prepi_pi_user }}/.config/pulse"
    - "/home/{{ prepi_pi_user }}/.config/systemd/user"

- name: Create PulseAudio default configuration
  copy:
    src: "/etc/pulse/default.pa"
    dest: "/home/{{ prepi_pi_user }}/.config/pulse/default.pa"
    remote_src: yes
    mode: 0644
  register: config_default

- name: Add configuration options to PulseAudio daemon
  lineinfile:
    path: "/home/{{ prepi_pi_user }}/.config/pulse/daemon.conf"
    line: "{{ item }}"
  loop:
    - "enable-shm = no"
    - "exit-idle-time = -1"

- name: Create PulseAudio systemd unit socket
  copy:
    src: "config/systemd/user/pulseaudio.socket"
    dest: "/home/{{ prepi_pi_user }}/.config/systemd/user/pulseaudio.socket"
    mode: 0644

- name: Create PulseAudio systemd unit socket
  template:
    src: "config/systemd/user/pulseaudio.service"
    dest: "/home/{{ prepi_pi_user }}/.config/systemd/user/pulseaudio.service"
    mode: 0644

- name: Start PulseAudio systemd service and socket
  systemd:
    name: pulseaudio
    enabled: yes
    scope: user
    state: started
    daemon-reload: yes

- name: Start systemd --user units during the boot process
  command:
    loginctl enable-linger {{ prepi_pi_user }}
  when: prepi_pulseaudio_daemon is defined and prepi_pulseaudio_daemon | bool
  changed_when: no
  become: yes

- name: Ensure tsched=0 is set for module-udev-detect
  lineinfile:
    path: /home/{{ prepi_pi_user }}/.config/pulse/default.pa
    regexp: "^load-module module-udev-detect"
    line: "load-module module-udev-detect tsched=0"
  register: config_tsched

# A handler should be use in this case but for some reasons
# there is a bug with the systemd module and the scope not
# keep as user.
- name: Restart PulseAudio if configuration changed
  systemd:
    name: pulseaudio
    scope: user
    state: restarted
  when: config_default.changed or config_tsched.changed
