---
- name: Install pulseaudio sound server
  package:
    name:
      - pulseaudio
      - pulseaudio-utils

- name: Add {{ prepi_pi_user }} user pulse-access and pulse groups
  user:
    name: "{{ prepi_pi_user }}"
    append: yes
    groups:
      - pulse-access
      - pulse

- name: Ensure tsched=0 is set for module-udev-detect
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: "^load-module module-udev-detect"
    line: "load-module module-udev-detect tsched=0"
  notify: restart-pulseaudio
