---
- name: Install pulseaudio sound server
  package:
    name:
      - pulseaudio
      - pulseaudio-utils

- name: Create PulseAudio systemd unit service and socket
  copy:
    src: "config/systemd/user/{{ item }}"
    dest: "/home/{{ prepi_pi_user }}/.config/systemd/user/{{ item }}"
    owner: "{{ prepi_pi_user }}"
    group: "{{ prepi_pi_user }}"
    mode: 0644
  loop:
    - pulseaudio.service
    - pulseaudio.socket
  notify: daemon-reload-user

- name: Force all notified handlers to run at this point
  meta: flush_handlers

- name: Start PulseAudio systemd service and socket
  systemd:
    name: "{{ item }}"
    enabled: yes
    scope: user
    state: started
  loop:
    - pulseaudio.service
    - pulseaudio.socket

- name: Ensure tsched=0 is set for module-udev-detect
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: "^load-module module-udev-detect"
    line: "load-module module-udev-detect tsched=0"
  notify: restart-pulseaudio
